### ISSUE TITLE
A suggestion to enable AirPrint for some hp printers

### ISSUE THREAD

**Issue by THENEBYS** [olbat/dockerfiles#61]
According to https://developers.hp.com/hp-linux-imaging-and-printing/binary_plugin.html , Some HP printers require proprietary software technologies to allow full access to printer features and performance.  Unfortunately, these technologies cannot be open sourced, but to resolve this HP uses a binary plug-in for these printers.This may cause some printers like p1108 can be found in iOS but won’t print anything.So I manually download the hp plug-in
from https://www.openprinting.org/download/printdriver/auxfiles/HP/plugins/hplip-3.21.6-plugin.run ,and config it.Now the AirPrint works fine with my hp p1108.

**Comment by THENEBYS** [comment]
So I wonder if there is a way you can add this part to your project. I don’t know about how to programming,I just provide a suggestion and how I solved the AirPrint issue,thanks!

**Comment by olbat** [comment]
Hello 👋 

No I don't think that this driver will ever be part of this project, for different reasons:
1. these drivers are not open-source, their license probably have some restrictive clauses about who can distribute them and how
2. if there is an EULA to accept, it will definitely not be possible to distribute the drivers in this project
3. starting to include support for random proprietary drivers for every printers brands will be very high maintenance for me

Here is the basic rule of thumb: if the driver you need is packaged and distributed by the Debian team, it can be included in this image. Otherwise it won't be.

**Comment by olbat** [comment]
Now you always have the option to build a new image which will include the drivers you need on the top of this one.
Just create a new _Dockerfile_ and mention this image as a base then add what you need to add.
(_Dockerfiles_ from this repository are licensed under the tems of the GNU GPLv3 license).

**Comment by THENEBYS** [comment]
👌I understand，thank you very much😄
