### ISSUE TITLE
Could you tag your docker image

### ISSUE THREAD

**Issue by obeyler** [olbat/dockerfiles#79]
As put in production a latest image is always a bad practice, do you plan to tag the image on docker hub ?

**Comment by olbat** [comment]
Hey 👋 Sorry for the late answer.

Sure, the main idea was not to overload Docker Hub with tags as the images are generated daily. I had to change build to be weekly instead of daily anyway since GitLab CI last changes wrt. their open-source CI minutes credit policy. So now it doesn't matter so much, I'll start to tag the images with the yyyy-mm-dd format.

**Comment by obeyler** [comment]
May you juste have to tag only when you commit some change not daily

**Comment by olbat** [comment]
> May you juste have to tag only when you commit some change not daily

The image tagging is for the packages that are being updated on the Debian packages registry, not for code changes.
